<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DevendraS-130398" failures="12" tests="61" name="All Test case Run" time="663.326" errors="0" timestamp="12 Mar 2024 12:21:48 GMT">
  <testcase classname="com.crm.qa.testcases.CurrencyMasterListingPageTest" name="verifyhomepage" time="3.026"/>
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="verifyHomePageTitleTest" time="3.013"/>
  <testcase classname="com.crm.qa.testcases.RegionCodeCreationPageTest" name="verifyhomepage" time="3.01"/>
  <testcase classname="com.crm.qa.testcases.NewCountrycreationPageTest" name="verifyhomepage" time="3.016"/>
  <testcase classname="com.crm.qa.testcases.Supplier_GSTIN_MasterListingPageTest" name="verifyhomepage" time="3.025"/>
  <testcase classname="com.crm.qa.testcases.priority_MasterListingPageTest" name="verifyhomepage" time="3.033"/>
  <testcase classname="com.crm.qa.testcases.StateCodeCreationPageTest" name="verifyhomepage" time="3.033"/>
  <testcase classname="com.crm.qa.testcases.NewCartcreationPageTest" name="verifyhomepage" time="3.025"/>
  <testcase classname="com.crm.qa.testcases.Airport_Warehouse_MasterListingPageTest" name="verifyhomepage" time="3.007"/>
  <testcase classname="com.crm.qa.testcases.FreightForwarder_MasterListingPageTest" name="verifyhomepage" time="3.014"/>
  <testcase classname="com.crm.qa.testcases.NewCurrancycreationPageTest" name="verifyhomepage" time="3.031"/>
  <testcase classname="com.crm.qa.testcases.CartMasterListingPageTest" name="verifyhomepage" time="3.032"/>
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="loginPageTitleTest" time="0.01"/>
  <testcase classname="com.crm.qa.testcases.NewHSCodeCreationPageTest" name="verifyhomepage" time="3.023"/>
  <testcase classname="com.crm.qa.testcases.State_MasterListingPageTest" name="verifyhomepage" time="3.035"/>
  <testcase classname="com.crm.qa.testcases.Region_MasterListingPageTest" name="verifyhomepage" time="3.011"/>
  <testcase classname="com.crm.qa.testcases.HSCode_MasterListingPageTest" name="verifyhomepage" time="3.018"/>
  <testcase classname="com.crm.qa.testcases.AircraftCreationPageTest" name="verifyhomepage" time="3.017"/>
  <testcase classname="com.crm.qa.testcases.Aircraft_MasterListingPageTest" name="verifyhomepage" time="3.014"/>
  <testcase classname="com.crm.qa.testcases.CurrencyMasterListingPageTest" name="verifyCurrancyListingpage" time="7.093"/>
  <testcase classname="com.crm.qa.testcases.NewCountrycreationPageTest" name="verifyCountryListingpage" time="7.07"/>
  <testcase classname="com.crm.qa.testcases.RegionCodeCreationPageTest" name="verifyRegionListingpage" time="6.903"/>
  <testcase classname="com.crm.qa.testcases.Supplier_GSTIN_MasterListingPageTest" name="verifySupplier_GSTINListingpage" time="6.927"/>
  <testcase classname="com.crm.qa.testcases.priority_MasterListingPageTest" name="verifypriorityListingpage" time="7.573">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/hs-code/list] but found [https://qaspicexpress.kargo360tech.com/dashboard]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/hs-code/list] but found [https://qaspicexpress.kargo360tech.com/dashboard]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.priority_MasterListingPageTest.verifypriorityListingpage(priority_MasterListingPageTest.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifypriorityListingpage -->
  <testcase classname="com.crm.qa.testcases.StateCodeCreationPageTest" name="verifyStateListingpage" time="6.78"/>
  <testcase classname="com.crm.qa.testcases.NewCartcreationPageTest" name="verifyCartListingpage" time="7.43"/>
  <testcase classname="com.crm.qa.testcases.Airport_Warehouse_MasterListingPageTest" name="verifyAircraftListingpage" time="7.079"/>
  <testcase classname="com.crm.qa.testcases.CountryMasterListingPageTest" name="verifyCountryListingpage" time="7.247"/>
  <testcase classname="com.crm.qa.testcases.FreightForwarder_MasterListingPageTest" name="verifyFreightForwarderListingpage" time="7.214"/>
  <testcase classname="com.crm.qa.testcases.NewCurrancycreationPageTest" name="verifyCurrancyListingpage" time="7.089"/>
  <testcase classname="com.crm.qa.testcases.CartMasterListingPageTest" name="verifyCartListingpage" time="6.977"/>
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="invalidLogin" time="3.26"/>
  <testcase classname="com.crm.qa.testcases.NewHSCodeCreationPageTest" name="verifyFreightForwarderListingpage" time="7.387"/>
  <testcase classname="com.crm.qa.testcases.State_MasterListingPageTest" name="verifyStateListingpage" time="7.028"/>
  <testcase classname="com.crm.qa.testcases.Region_MasterListingPageTest" name="verifyRegionListingpage" time="7.154"/>
  <testcase classname="com.crm.qa.testcases.HSCode_MasterListingPageTest" name="verifyFreightForwarderListingpage" time="7.239"/>
  <testcase classname="com.crm.qa.testcases.AircraftCreationPageTest" name="verifyAircraftListingpage" time="7.104"/>
  <testcase classname="com.crm.qa.testcases.Aircraft_MasterListingPageTest" name="verifyAircraftListingpage" time="6.972"/>
  <testcase classname="com.crm.qa.testcases.RegionCodeCreationPageTest" name="ClickonNewRegionButton" time="10.534"/>
  <testcase classname="com.crm.qa.testcases.StateCodeCreationPageTest" name="ClickonNewStateButton" time="10.242"/>
  <testcase classname="com.crm.qa.testcases.NewCountrycreationPageTest" name="ClickonNewCountryButton" time="8.494"/>
  <testcase classname="com.crm.qa.testcases.NewCurrancycreationPageTest" name="ClickonNewCurrancyButton" time="9.124"/>
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="invalidUser" time="3.269"/>
  <testcase classname="com.crm.qa.testcases.NewFreightForwarderCreationPageTest" name="ClickonNewFreightForwarderButton" time="10.305"/>
  <testcase classname="com.crm.qa.testcases.NewCartcreationPageTest" name="ClickonNewCartButton" time="8.191"/>
  <testcase classname="com.crm.qa.testcases.AircraftCreationPageTest" name="ClickonNewAircraftButton" time="10.601"/>
  <testcase classname="com.crm.qa.testcases.NewHSCodeCreationPageTest" name="ClickonNewFreightForwarderButton" time="10.332"/>
  <testcase classname="com.crm.qa.testcases.RegionCodeCreationPageTest" name="RegionCreationPossitiveflow" time="13.209">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/region/list] but found [https://qaspicexpress.kargo360tech.com/region/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/region/list] but found [https://qaspicexpress.kargo360tech.com/region/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.RegionCodeCreationPageTest.RegionCreationPossitiveflow(RegionCodeCreationPageTest.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RegionCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.Supplier_GSTINCreationPageTest" name="Supplier_GSTIN_Possitiveflow" time="16.077">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/supplier-gstin/list] but found [https://qaspicexpress.kargo360tech.com/supplier-gstin/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/supplier-gstin/list] but found [https://qaspicexpress.kargo360tech.com/supplier-gstin/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.Supplier_GSTINCreationPageTest.Supplier_GSTIN_Possitiveflow(Supplier_GSTINCreationPageTest.java:248)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Supplier_GSTIN_Possitiveflow -->
  <testcase classname="com.crm.qa.testcases.NewCountrycreationPageTest" name="CountryCreationPossitiveflow" time="11.177">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/country/list] but found [https://qaspicexpress.kargo360tech.com/country/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/country/list] but found [https://qaspicexpress.kargo360tech.com/country/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.NewCountrycreationPageTest.CountryCreationPossitiveflow(NewCountrycreationPageTest.java:136)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CountryCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.NewCurrancycreationPageTest" name="CartCreationPossitiveflow" time="9.89">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/currency/list] but found [https://qaspicexpress.kargo360tech.com/currency/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/currency/list] but found [https://qaspicexpress.kargo360tech.com/currency/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.NewCurrancycreationPageTest.CartCreationPossitiveflow(NewCurrancycreationPageTest.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CartCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="invalidPass" time="3.313"/>
  <testcase classname="com.crm.qa.testcases.NewFreightForwarderCreationPageTest" name="FreightForwarderCreationPossitiveflow" time="13.759">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/freight-forwarder/list] but found [https://qaspicexpress.kargo360tech.com/freight-forwarder/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/freight-forwarder/list] but found [https://qaspicexpress.kargo360tech.com/freight-forwarder/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.NewFreightForwarderCreationPageTest.FreightForwarderCreationPossitiveflow(NewFreightForwarderCreationPageTest.java:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FreightForwarderCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.StateCodeCreationPageTest" name="StateCreationPossitiveflow" time="13.177">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/state/list] but found [https://qaspicexpress.kargo360tech.com/state/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/state/list] but found [https://qaspicexpress.kargo360tech.com/state/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.StateCodeCreationPageTest.StateCreationPossitiveflow(StateCodeCreationPageTest.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- StateCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.AircraftCreationPageTest" name="AircraftCreationPossitiveflow" time="15.825">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/aircraft/list] but found [https://qaspicexpress.kargo360tech.com/aircraft/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/aircraft/list] but found [https://qaspicexpress.kargo360tech.com/aircraft/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.AircraftCreationPageTest.AircraftCreationPossitiveflow(AircraftCreationPageTest.java:257)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AircraftCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.NewCartcreationPageTest" name="CartCreationPossitiveflow" time="11.019">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/cart/list] but found [https://qaspicexpress.kargo360tech.com/cart/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/cart/list] but found [https://qaspicexpress.kargo360tech.com/cart/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.NewCartcreationPageTest.CartCreationPossitiveflow(NewCartcreationPageTest.java:128)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CartCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.Airport_WarehouseCreationPageTest" name="WarehouseCreationPossitiveflow" time="16.288">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/airport/list] but found [https://qaspicexpress.kargo360tech.com/airport/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/airport/list] but found [https://qaspicexpress.kargo360tech.com/airport/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.Airport_WarehouseCreationPageTest.WarehouseCreationPossitiveflow(Airport_WarehouseCreationPageTest.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- WarehouseCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.NewHSCodeCreationPageTest" name="FreightForwarderCreationPossitiveflow" time="12.675">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/hs-code/list] but found [https://qaspicexpress.kargo360tech.com/hs-code/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/hs-code/list] but found [https://qaspicexpress.kargo360tech.com/hs-code/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.NewHSCodeCreationPageTest.FreightForwarderCreationPossitiveflow(NewHSCodeCreationPageTest.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FreightForwarderCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.Airport_WarehouseCreationPageTest" name="AirportCreationPossitiveflow" time="16.051">
    <failure type="java.lang.AssertionError" message="expected [https://qaspicexpress.kargo360tech.com/airport/list] but found [https://qaspicexpress.kargo360tech.com/airport/create]">
      <![CDATA[java.lang.AssertionError: expected [https://qaspicexpress.kargo360tech.com/airport/list] but found [https://qaspicexpress.kargo360tech.com/airport/create]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.Airport_WarehouseCreationPageTest.AirportCreationPossitiveflow(Airport_WarehouseCreationPageTest.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AirportCreationPossitiveflow -->
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="noCredentials" time="3.215"/>
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="loginTest" time="2.264"/>
</testsuite> <!-- All Test case Run -->
